### ISSUE TITLE
Меня держут в заложниках

### ISSUE THREAD

**Issue by honakac** [Eraser-Team/ru-joke#1]
Куплю пива, возьму в рот

**Comment by AnchoSus** [comment]
Лень

**Comment by honakac** [comment]
😭😭😭👨‍❤️‍👨👨‍❤️‍💋‍👨🫄

**Comment by AnchoSus** [comment]
> 😭😭😭👨‍❤️‍👨👨‍❤️‍💋‍👨🫄

🤫🧏

**Comment by honakac** [comment]
отчим №69 сделай сигму слово пацана 1488%

**Comment by AnchoSus** [comment]
😙🙂🙋

**Comment by honakac** [comment]
🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️ Я пи

**Comment by AnchoSus** [comment]
Я тоже🏁🏁🏁

**Comment by honakac** [comment]
🏴󠁧󠁢󠁳󠁣󠁴󠁿SCOTLAND FOREVER🏴󠁧󠁢󠁳󠁣󠁴󠁿🏳️‍⚧️
